name: Commit validations

on:
  push:
    branches:
      - 'feature/*'

jobs:
  validate-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run Linters
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Run build
        run: npm run build
